# Basic config
baseURL = "https://zihengjackchen.github.io/iprism-page/"
theme = ["hugo-video", "hugo-simple"]
languageCode = "en"                # zh-Hans
title = "Hugo Simple"
copyright = "© 2024 Ziheng (Jack) Chen"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slugorfilename/"
tags = "/blog/:slug"

[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
title = "Dependable AVs"
description = "Open-Source Research Projects for Making Autonomous Vehicles Dependable"
favicon = "images/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = false
hideRSSLink = true
customCSS = ["main.css"]
[params.author]
name = "Ziheng (Jack) Chen"
email = "zihengchen2000@gmail.com"





[outputs]
# Generate RSS for home only.
section = ["html"]
taxonomy = ["html"]
term = ["html"]
